// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SellBotLk.Api.Data;

#nullable disable

namespace SellBotLk.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321094941_20260320_InitialSchema")]
    partial class _20260320_InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SellBotLk.Api.Models.Entities.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Context")
                        .HasColumnType("json");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("SellBotLk.Api.Models.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastOrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSpend")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SellBotLk.Api.Models.Entities.DailyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnomalyCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date");

                    b.Property<string>("ReportText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TopProductId")
                        .HasColumnType("int");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReportDate")
                        .IsUnique();

                    b.HasIndex("TopProductId");

                    b.ToTable("DailyReports");
                });

            modelBuilder.Entity("SellBotLk.Api.Models.Entities.DeliveryZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("EstimatedDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("FreeDeliveryThreshold")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryZones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryFee = 300m,
                            EstimatedDays = 1,
                            FreeDeliveryThreshold = 50000m,
                            IsActive = true,
                            ZoneName = "Colombo"
                        },
                        new
                        {
                            Id = 2,
                            DeliveryFee = 400m,
                            EstimatedDays = 1,
                            FreeDeliveryThreshold = 50000m,
                            IsActive = true,
                            ZoneName = "Gampaha"
                        },
                        new
                        {
                            Id = 3,
                            DeliveryFee = 500m,
                            EstimatedDays = 2,
                            FreeDeliveryThreshold = 60000m,
                            IsActive = true,
                            ZoneName = "Kalutara"
                        },
                        new
                        {
                            Id = 4,
                            DeliveryFee = 800m,
                            EstimatedDays = 2,
                            FreeDeliveryThreshold = 70000m,
                            IsActive = true,
                            ZoneName = "Kandy"
                        },
                        new
                        {
                            Id = 5,
                            DeliveryFee = 900m,
                            EstimatedDays = 2,
                            FreeDeliveryThreshold = 70000m,
                            IsActive = true,
                            ZoneName = "Matale"
                        },
                        new
                        {
                            Id = 6,
                            DeliveryFee = 1000m,
                            EstimatedDays = 3,
                            FreeDeliveryThreshold = 80000m,
                            IsActive = true,
                            ZoneName = "Nuwara Eliya"
                        },
                        new
                        {
                            Id = 7,
                            DeliveryFee = 900m,
                            EstimatedDays = 2,
                            FreeDeliveryThreshold = 70000m,
                            IsActive = true,
                            ZoneName = "Galle"
                        },
                        new
                        {
                            Id = 8,
                            DeliveryFee = 1000m,
                            EstimatedDays = 3,
                            FreeDeliveryThreshold = 80000m,
                            IsActive = true,
                            ZoneName = "Matara"
                        },
                        new
                        {
                            Id = 9,
                            DeliveryFee = 1200m,
                            EstimatedDays = 3,
                            FreeDeliveryThreshold = 80000m,
                            IsActive = true,
                            ZoneName = "Hambantota"
                        },
                        new
                        {
                            Id = 10,
                            DeliveryFee = 1500m,
                            EstimatedDays = 4,
                            FreeDeliveryThreshold = 100000m,
                            IsActive = true,
                            ZoneName = "Jaffna"
                        },
                        new
                        {
                            Id = 11,
                            DeliveryFee = 1600m,
                            EstimatedDays = 4,
                            FreeDeliveryThreshold = 100000m,
                            IsActive = true,
                            ZoneName = "Kilinochchi"
                        },
                        new
                        {
                            Id = 12,
                            DeliveryFee = 1600m,
                            EstimatedDays = 4,
                            FreeDeliveryThreshold = 100000m,
                            IsActive = true,
                            ZoneName = "Mannar"
                        },
                        new
                        {
                            Id = 13,
                            DeliveryFee = 1500m,
                            EstimatedDays = 4,
                            FreeDeliveryThreshold = 100000m,
                            IsActive = true,
                            ZoneName = "Vavuniya"
                        },
                        new
                        {
                            Id = 14,
                            DeliveryFee = 1400m,
                            EstimatedDays = 3,
                            FreeDeliveryThreshold = 90000m,
                            IsActive = true,
                            ZoneName = "Trincomalee"
                        },
                        new
                        {
                            Id = 15,
                            DeliveryFee = 1400m,
                            EstimatedDays = 3,
                            FreeDeliveryThreshold = 90000m,
                            IsActive = true,
                            ZoneName = "Batticaloa"
                        },
                        new
                        {
                            Id = 16,
                            DeliveryFee = 1300m,
                            EstimatedDays = 3,
                            FreeDeliveryThreshold = 90000m,
                            IsActive = true,
                            ZoneName = "Ampara"
                        },
                        new
                        {
                            Id = 17,
                            DeliveryFee = 800m,
                            EstimatedDays = 2,
                            FreeDeliveryThreshold = 70000m,
                            IsActive = true,
                            ZoneName = "Ratnapura"
                        },
                        new
                        {
                            Id = 18,
                            DeliveryFee = 700m,
                            EstimatedDays = 2,
                            FreeDeliveryThreshold = 70000m,
                            IsActive = true,
                            ZoneName = "Kegalle"
                        },
                        new
                        {
                            Id = 19,
                            DeliveryFee = 700m,
                            EstimatedDays = 2,
                            FreeDeliveryThreshold = 70000m,
                            IsActive = true,
                            ZoneName = "Kurunegala"
                        },
                        new
                        {
                            Id = 20,
                            DeliveryFee = 800m,
                            EstimatedDays = 2,
                            FreeDeliveryThreshold = 70000m,
                            IsActive = true,
                            ZoneName = "Puttalam"
                        },
                        new
                        {
                            Id = 21,
                            DeliveryFee = 1100m,
                            EstimatedDays = 3,
                            FreeDeliveryThreshold = 80000m,
                            IsActive = true,
                            ZoneName = "Anuradhapura"
                        },
                        new
                        {
                            Id = 22,
                            DeliveryFee = 1100m,
                            EstimatedDays = 3,
                            FreeDeliveryThreshold = 80000m,
                            IsActive = true,
                            ZoneName = "Polonnaruwa"
                        },
                        new
                        {
                            Id = 23,
                            DeliveryFee = 1000m,
                            EstimatedDays = 3,
                            FreeDeliveryThreshold = 80000m,
                            IsActive = true,
                            ZoneName = "Badulla"
                        },
                        new
                        {
                            Id = 24,
                            DeliveryFee = 1100m,
                            EstimatedDays = 3,
                            FreeDeliveryThreshold = 80000m,
                            IsActive = true,
                            ZoneName = "Monaragala"
                        },
                        new
                        {
                            Id = 25,
                            DeliveryFee = 1700m,
                            EstimatedDays = 5,
                            FreeDeliveryThreshold = 100000m,
                            IsActive = true,
                            ZoneName = "Mullaitivu"
                        });
                });

            modelBuilder.Entity("SellBotLk.Api.Models.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DocumentDate")
                        .HasColumnType("date");

                    b.Property<string>("ExtractedData")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProcessingNotes")
                        .HasColumnType("longtext");

                    b.Property<string>("RawImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VendorName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("SellBotLk.Api.Models.Entities.InventoryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("int");

                    b.Property<int>("QuantityBefore")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryLogs");
                });

            modelBuilder.Entity("SellBotLk.Api.Models.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("DeliveryArea")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("FraudReason")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFraudFlagged")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SellBotLk.Api.Models.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("NegotiatedPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SellBotLk.Api.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BulkDiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("BulkMinQty")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StockQty")
                        .HasColumnType("int");

                    b.Property<string>("Style")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsActive");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BulkDiscountPercent = 10m,
                            BulkMinQty = 5,
                            Category = "Chair",
                            Color = "Black",
                            CreatedAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonomic executive chair with lumbar support, armrests, and height adjustment.",
                            IsActive = true,
                            LowStockThreshold = 5,
                            Material = "Leather",
                            MinPrice = 22000m,
                            Name = "Executive High-Back Leather Chair",
                            Price = 28500m,
                            StockQty = 20,
                            Style = "Modern"
                        },
                        new
                        {
                            Id = 2,
                            BulkDiscountPercent = 8m,
                            BulkMinQty = 3,
                            Category = "Table",
                            Color = "Natural Wood",
                            CreatedAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hand-crafted solid teak dining table, seats 6 comfortably. Includes protective lacquer finish.",
                            IsActive = true,
                            LowStockThreshold = 2,
                            Material = "Solid Teak",
                            MinPrice = 60000m,
                            Name = "Solid Teak Dining Table (6-seater)",
                            Price = 75000m,
                            StockQty = 8,
                            Style = "Traditional"
                        },
                        new
                        {
                            Id = 3,
                            BulkDiscountPercent = 5m,
                            BulkMinQty = 2,
                            Category = "Sofa",
                            Color = "Grey",
                            CreatedAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortable 3-seater sofa with removable cushion covers. Available in grey and beige.",
                            IsActive = true,
                            LowStockThreshold = 3,
                            Material = "Fabric",
                            MinPrice = 45000m,
                            Name = "Three-Seater Fabric Sofa",
                            Price = 55000m,
                            StockQty = 12,
                            Style = "Scandinavian"
                        },
                        new
                        {
                            Id = 4,
                            BulkDiscountPercent = 12m,
                            BulkMinQty = 4,
                            Category = "Desk",
                            Color = "White",
                            CreatedAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Spacious office desk with cable management and storage shelf. 140cm wide.",
                            IsActive = true,
                            LowStockThreshold = 4,
                            Material = "MDF + Steel",
                            MinPrice = 26000m,
                            Name = "Steel Frame Office Desk",
                            Price = 32000m,
                            StockQty = 15,
                            Style = "Modern"
                        },
                        new
                        {
                            Id = 5,
                            BulkDiscountPercent = 10m,
                            BulkMinQty = 5,
                            Category = "Storage",
                            Color = "Walnut",
                            CreatedAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "5-tier open bookshelf with metal side supports. Easy self-assembly.",
                            IsActive = true,
                            LowStockThreshold = 6,
                            Material = "Engineered Wood",
                            MinPrice = 14000m,
                            Name = "Wooden Bookshelf (5-tier)",
                            Price = 18500m,
                            StockQty = 25,
                            Style = "Industrial"
                        });
                });

            modelBuilder.Entity("SellBotLk.Api.Models.Entities.Conversation", b =>
                {
                    b.HasOne("SellBotLk.Api.Models.Entities.Customer", "Customer")
                        .WithMany("Conversations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SellBotLk.Api.Models.Entities.DailyReport", b =>
                {
                    b.HasOne("SellBotLk.Api.Models.Entities.Product", "TopProduct")
                        .WithMany("DailyReports")
                        .HasForeignKey("TopProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TopProduct");
                });

            modelBuilder.Entity("SellBotLk.Api.Models.Entities.Document", b =>
                {
                    b.HasOne("SellBotLk.Api.Models.Entities.Customer", "Customer")
                        .WithMany("Documents")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SellBotLk.Api.Models.Entities.InventoryLog", b =>
                {
                    b.HasOne("SellBotLk.Api.Models.Entities.Product", "Product")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SellBotLk.Api.Models.Entities.Order", b =>
                {
                    b.HasOne("SellBotLk.Api.Models.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SellBotLk.Api.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("SellBotLk.Api.Models.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SellBotLk.Api.Models.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SellBotLk.Api.Models.Entities.Customer", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Documents");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SellBotLk.Api.Models.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SellBotLk.Api.Models.Entities.Product", b =>
                {
                    b.Navigation("DailyReports");

                    b.Navigation("InventoryLogs");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
