using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SellBotLk.Api.Models.Entities;

/// <summary>
/// AI-generated daily business summary report.
///
/// Created once per calendar day by the DailyReportJob (Hangfire, 7AM).
/// The ReportDate column is UNIQUE — only one report per day is allowed.
/// ReportService uses an upsert pattern (insert or update) to handle reruns.
///
/// ReportText is the full Gemini-generated narrative sent to the owner via
/// WhatsApp. The structured metrics (TotalOrders, TotalRevenue, etc.) are
/// also stored in dedicated columns so the admin dashboard can display
/// charts without parsing the text narrative.
/// </summary>
[Table("DailyReports")]
public class DailyReport
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    /// The calendar date this report covers (yesterday's data when sent at 7AM).
    /// UNIQUE constraint — enforced at DB level and in EF model builder.
    /// </summary>
    [Required]
    public DateOnly ReportDate { get; set; }

    /// <summary>
    /// Total number of orders placed on ReportDate.
    /// Includes all statuses — even cancelled orders are counted
    /// so the owner can see cancellation rates.
    /// </summary>
    [Required]
    public int TotalOrders { get; set; }

    /// <summary>
    /// Total revenue in LKR from confirmed/delivered orders on ReportDate.
    /// Cancelled and FraudPending orders are excluded from revenue.
    /// </summary>
    [Required]
    [Column(TypeName = "decimal(12,2)")]
    public decimal TotalRevenue { get; set; }

    /// <summary>
    /// Foreign key to the best-selling product on ReportDate (by units sold).
    /// Nullable — if no orders were placed, there is no top product.
    /// Shown in the daily WhatsApp report and on the dashboard home card.
    /// </summary>
    public int? TopProductId { get; set; }

    /// <summary>
    /// Count of orders flagged by FraudDetectionService on ReportDate.
    /// Shown in the report so the owner knows how many reviews they handled.
    /// </summary>
    public int AnomalyCount { get; set; } = 0;

    /// <summary>
    /// Full AI-generated narrative report text.
    /// Generated by Gemini with all daily metrics injected as context.
    /// Formatted with emojis and line breaks for WhatsApp readability.
    /// Maximum ~3,500 characters to stay within WhatsApp's 4,096 char limit.
    ///
    /// Example:
    ///   "Good morning! 🌅 Yesterday's summary:
    ///    📦 12 orders | 💰 LKR 48,500 revenue
    ///    🏆 Top seller: Office Chair (5 units)
    ///    ⚠️ 1 fraud flag reviewed and approved
    ///    📉 Low stock: Dining Table (2 left)"
    /// </summary>
    [Required]
    public string ReportText { get; set; } = null!;

    /// <summary>
    /// UTC timestamp when this report was sent to the owner via WhatsApp.
    /// Null = not yet sent (e.g. generated but WhatsApp API was down).
    /// DailyReportJob retries unsent reports on next run.
    /// </summary>
    public DateTime? SentAt { get; set; }

    // ── Navigation properties ──────────────────────────────────────────────

    [ForeignKey(nameof(TopProductId))]
    public Product? TopProduct { get; set; }
}