using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SellBotLk.Api.Models.Entities;

/// <summary>
/// Lifecycle state of an order.
/// Transitions: Pending → Confirmed → Processing → Dispatched → Delivered
///              Any state (except Delivered) → Cancelled
///              FraudPending: order is held for owner review before it can progress
/// </summary>
public enum OrderStatus
{
    Pending = 0,
    Confirmed = 1,
    Processing = 2,
    Dispatched = 3,
    Delivered = 4,
    Cancelled = 5,
    FraudPending = 6
}

/// <summary>
/// Payment state of an order.
/// </summary>
public enum PaymentStatus
{
    Unpaid = 0,
    Paid = 1,
    Refunded = 2
}

/// <summary>
/// Represents a customer order created via WhatsApp conversation.
/// Every order carries a human-readable OrderNumber (ORD-2026-001 format)
/// used in all customer-facing messages.
/// </summary>
[Table("Orders")]
public class Order
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    /// Human-readable order number in format ORD-YYYY-NNN.
    /// Generated by OrderNumberGenerator service. Unique, never reused.
    /// Shared with customers in confirmations and status updates.
    /// </summary>
    [Required]
    [MaxLength(20)]
    public string OrderNumber { get; set; } = null!;

    /// <summary>
    /// Foreign key to the customer who placed this order.
    /// </summary>
    [Required]
    public int CustomerId { get; set; }

    /// <summary>
    /// Current lifecycle state. See OrderStatus enum for valid transitions.
    /// </summary>
    [Required]
    public OrderStatus Status { get; set; } = OrderStatus.Pending;

    /// <summary>
    /// Total order value in LKR including all items.
    /// Calculated from OrderItems at time of order creation.
    /// Does NOT update if product prices change later.
    /// </summary>
    [Required]
    [Column(TypeName = "decimal(12,2)")]
    public decimal TotalAmount { get; set; }

    /// <summary>
    /// Total discount applied to this order (bulk or negotiated).
    /// Stored separately so original TotalAmount is preserved for reporting.
    /// </summary>
    [Column(TypeName = "decimal(12,2)")]
    public decimal DiscountAmount { get; set; } = 0.00m;

    /// <summary>
    /// Current payment state.
    /// Updated by DocumentService when a payment slip is verified.
    /// </summary>
    [Required]
    public PaymentStatus PaymentStatus { get; set; } = PaymentStatus.Unpaid;

    /// <summary>
    /// Bank transfer reference number extracted from payment slip by Gemini Vision.
    /// Stored for manual reconciliation if needed.
    /// </summary>
    [MaxLength(100)]
    public string? PaymentReference { get; set; }

    /// <summary>
    /// Full delivery address as provided by the customer via WhatsApp.
    /// Extracted by Gemini from conversational text (e.g. "No 12, Galle Road, Colombo 3").
    /// </summary>
    public string? DeliveryAddress { get; set; }

    /// <summary>
    /// City or district for delivery routing. Matched against DeliveryZones table
    /// by DeliveryService to determine delivery fee and estimated days.
    /// </summary>
    [MaxLength(100)]
    public string? DeliveryArea { get; set; }

    /// <summary>
    /// AI-extracted special instructions from the customer's message.
    /// Example: "Please wrap in bubble wrap", "Call before delivery".
    /// </summary>
    public string? Notes { get; set; }

    /// <summary>
    /// True when FraudDetectionService has flagged this order as suspicious.
    /// Flagged orders are set to FraudPending status and held for owner review.
    /// </summary>
    public bool IsFraudFlagged { get; set; } = false;

    /// <summary>
    /// AI-generated explanation of why this order was flagged.
    /// Example: "3rd order from this number in 8 minutes. Quantity 50 is unusually high."
    /// Shown to owner in the fraud review queue on the admin dashboard.
    /// </summary>
    public string? FraudReason { get; set; }

    /// <summary>
    /// Timestamp of order creation.
    /// </summary>
    /// 
    
    [Required]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
/// Delivery driver instructions or notes.
/// Set by admin when dispatching the order.
/// Example: "Call customer before arriving", "Leave at gate".
/// </summary>
[MaxLength(500)]
public string? DriverNote { get; set; }

    /// <summary>
    /// Timestamp of the last status change.
    /// </summary>
    [Required]
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    // ── Navigation properties ──────────────────────────────────────────────

    [ForeignKey(nameof(CustomerId))]
    public Customer Customer { get; set; } = null!;

    public ICollection<OrderItem> Items { get; set; } = new List<OrderItem>();
}